"use client";

import { Activity, Loader2, Sparkles } from "lucide-react";
import { useEffect, useRef } from "react";

import { SignalCard } from "@/components/signals/signal-card";
import { SignalRefreshButton } from "@/components/signals/signal-refresh-button";
import { FilterSegmented } from "@/components/tasks/task-filter-bar";
import { LastUpdated } from "@/components/avir/last-updated";
import { Skeleton } from "@/components/ui/skeleton";
import { ACTION_LABELS } from "@/lib/design/signals";
import { useAircraftSignals } from "@/lib/queries/use-aircraft-signals";
import { useRecentSignalActions } from "@/lib/queries/use-recent-signal-actions";
import { useSignalActions } from "@/lib/mutations/use-signal-actions";
import { useSignalRealtime } from "@/lib/realtime/use-signal-realtime";
import { useAuth } from "@/lib/providers/auth-provider";
import { timeAgo } from "@/lib/utils";
import { useState } from "react";

/** Signals tab: AI Signals (generated by Claude) + the Recent Actions record. */
export function AircraftSignalsTab({ aircraftId }: { aircraftId: string }) {
  const { orgId, user } = useAuth();
  useSignalRealtime(orgId);
  const { generate } = useSignalActions();
  const [filter, setFilter] = useState<"active" | "all" | "done">("active");

  const { data, isLoading } = useAircraftSignals(aircraftId, filter !== "active");
  const { data: actions } = useRecentSignalActions(aircraftId);

  const run = data?.latest_run ?? null;
  const generating = run?.status === "started";

  // Auto-generate on first view when this aircraft has no signals yet.
  const triggered = useRef(false);
  useEffect(() => {
    if (!data || triggered.current) return;
    const hasActive = data.signals.some((s) => s.is_active);
    if (!hasActive && run?.status !== "started") {
      triggered.current = true;
      generate(aircraftId, { force: false, runType: "triggered_by_event" }).catch(() => {});
    }
  }, [data, aircraftId, generate, run?.status]);

  const signals = (data?.signals ?? []).filter((s) =>
    filter === "all" ? true : filter === "done" ? !s.is_active : s.is_active,
  );

  return (
    <div className="p-6">
      {/* Header */}
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-3">
          <h2 className="inline-flex items-center gap-2 font-serif text-xl text-foreground">
            <Sparkles className="h-4 w-4 text-primary" /> AI Signals
          </h2>
          {run?.generated_at_utc && (
            <span className="font-mono text-eyebrow uppercase text-label">
              Generated {timeAgo(run.generated_at_utc)}
            </span>
          )}
        </div>
        <div className="flex items-center gap-2">
          <FilterSegmented
            options={[
              { value: "active", label: "Active" },
              { value: "all", label: "All" },
              { value: "done", label: "Resolved" },
            ]}
            value={filter}
            onChange={(v) => setFilter(v as "active" | "all" | "done")}
          />
          <SignalRefreshButton aircraftId={aircraftId} />
        </div>
      </div>

      {/* Confidence legend */}
      <div className="mb-4 flex flex-wrap items-center gap-4 border border-border bg-surface/30 px-3 py-2 text-[11px] text-subtext">
        <span className="font-mono uppercase tracking-wider text-label">Confidence</span>
        <span className="inline-flex items-center gap-1.5"><span className="severity-dot bg-severity-low" /> High — strong evidence</span>
        <span className="inline-flex items-center gap-1.5"><span className="severity-dot bg-severity-medium" /> Medium — partial</span>
        <span className="inline-flex items-center gap-1.5"><span className="severity-dot bg-severity-high" /> Low — limited</span>
      </div>

      {/* Signals */}
      {isLoading ? (
        <div className="space-y-3">
          {[0, 1].map((i) => <Skeleton key={i} className="h-64 w-full" />)}
        </div>
      ) : generating && signals.length === 0 ? (
        <div className="flex min-h-[30vh] flex-col items-center justify-center text-center">
          <Loader2 className="h-6 w-6 animate-spin text-primary" />
          <p className="mt-3 text-sm text-subtext">Generating signals from this aircraft&apos;s data…</p>
          <p className="mt-1 font-mono text-eyebrow uppercase text-hint">Claude is analyzing tasks, state, and history</p>
        </div>
      ) : signals.length === 0 ? (
        <div className="flex min-h-[30vh] flex-col items-center justify-center text-center">
          <div className="mb-4 flex h-14 w-14 items-center justify-center border border-border bg-surface/40">
            <Activity className="h-6 w-6 text-label" strokeWidth={1.5} />
          </div>
          <h3 className="font-serif text-xl text-foreground">No active signals for this aircraft</h3>
          <p className="mt-2 max-w-md text-sm leading-relaxed text-subtext">
            Data is being monitored. Refresh to run a fresh analysis, or check that data is syncing
            from your source systems.
          </p>
        </div>
      ) : (
        <div className="grid gap-4 xl:grid-cols-2">
          {generating && (
            <div className="xl:col-span-2 flex items-center gap-2 border border-primary/30 bg-primary/5 px-3 py-2 text-xs text-primary">
              <Loader2 className="h-3.5 w-3.5 animate-spin" /> Generating fresh signals…
            </div>
          )}
          {signals.map((s) => (
            <SignalCard key={s.id} signal={s} />
          ))}
        </div>
      )}

      {/* Recent Actions — the calibration record */}
      <div className="mt-8 border-t border-border pt-5">
        <p className="eyebrow mb-3">Recent actions · calibration record</p>
        {!actions || actions.length === 0 ? (
          <p className="text-sm text-hint">No actions recorded yet.</p>
        ) : (
          <div className="divide-y divide-border border border-border">
            {actions.map((a) => (
              <div key={a.id} className="flex items-center gap-3 px-3 py-2 text-sm">
                <span className="font-mono text-eyebrow uppercase text-label">
                  {ACTION_LABELS[a.action_type] ?? a.action_type}
                </span>
                <span className="min-w-0 flex-1 truncate text-body">{a.signal_title ?? "—"}</span>
                {a.actor_user_id === user?.id && (
                  <span className="font-mono text-eyebrow uppercase text-hint">you</span>
                )}
                <LastUpdated at={a.created_at_utc} label="" className="shrink-0" />
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
